### ISSUE TITLE
Mac os 下会导入文件夹下的.DS_Store 文件，可否添加个过滤

### ISSUE THREAD

**Issue by lg8294** [xiaxiayige/FlutterAssetSync#2]
![image](https://user-images.githubusercontent.com/10041773/93838464-56e32780-fcbc-11ea-92b0-111ffb77378a.png)

**Comment by lg8294** [comment]
![image](https://user-images.githubusercontent.com/10041773/93838512-77ab7d00-fcbc-11ea-9c2b-3417919f7a5b.png)
![image](https://user-images.githubusercontent.com/10041773/93838531-84c86c00-fcbc-11ea-9138-af7d899dfe01.png)

**Comment by xiaxiayige** [comment]
已添加过滤，可以前往Android Studio 更新
