### ISSUE TITLE
支持Android Studio 4.2

### ISSUE THREAD

**Issue by DongXuanLei** [xiaxiayige/FlutterAssetSync#4]
什么时候能更新Android Studio插件呢？现在Android Studio 4.2搜索不到

**Comment by xiaxiayige** [comment]
> 什么时候能更新Android Studio插件呢？现在Android Studio 4.2搜索不到

可以搜索呀，前几天才更新了。我的Window Android studio4.2.1 可以正常搜索下载 你再试下，不行我发个离线包给你安装
